### ISSUE TITLE
Results Not Prioritize

### ISSUE THREAD

**Issue by markpanado** [blakek/zazu-emoj#1]
Why my emoj results not prioritize in list? Fallback takeovers the list.
![screen shot 2017-01-10 at 8 38 51 pm](https://cloud.githubusercontent.com/assets/3646720/21806544/d4e52870-d774-11e6-9e54-0e321537cdbf.png)

**Comment by blakek** [comment]
Hey @markpanado, thanks for taking the time to report this!

This is an upstream issue with Zazu (see https://github.com/tinytacoteam/zazu/issues/147).  Right now, plugins that respond faster are higher in the rankings.  Because zazu-emoj makes a network request, it will be slower than the fallback plugin results.

**Comment by blakek** [comment]
This should be working if you upgrade Zazu!
